# Generated by Django 4.2.13 on 2024-06-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='time',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='time',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
