# Generated by Django 4.2.13 on 2024-06-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_rename_comment_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='highestBid',
            field=models.DecimalField(decimal_places=2, default=models.FloatField(), max_digits=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='startingBid',
            field=models.FloatField(),
        ),
    ]
