# Generated by Django 4.2.13 on 2024-06-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_listing_highestbid_alter_listing_startingbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='highestBid',
            field=models.FloatField(default=models.FloatField()),
        ),
    ]
