# Generated by Django 4.2.13 on 2024-06-29 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_listing_category_alter_listing_highestbid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='starting',
            new_name='is_starting',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='listing',
        ),
        migrations.AddField(
            model_name='listing',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='highestBid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highest_bid', to='auctions.bid'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='startingBid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starting_bid', to='auctions.bid'),
        ),
    ]
