# Generated by Django 4.2.13 on 2024-06-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_rename_starting_bid_is_starting_remove_bid_listing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='highestBid',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='startingBid',
            field=models.FloatField(),
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
    ]
